import { SchoolConfig, NewsArticle } from '../types';
import { DEFAULT_THEME_CONFIG } from './themePresets';
import { DEFAULT_APPS_SCRIPT_WEB_APP_URL, DEFAULT_APPS_SCRIPT_FOLDER_ID } from './googleAppsScript';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  adminPassword: '',
  identity: {
    name: 'MGMP IPA KECAMATAN BENGKALIS',
    shortName: 'MGMP IPA Bengkalis',
    tagline: 'Wadah Kolaborasi, Inovasi & Pengembangan Profesionalisme Guru IPA SMP/MTs',
    npsn: '',
    akreditasi: 'Komunitas Belajar Terdaftar',
    logoUrl: '',
    faviconUrl: '',
    tickerEnabled: true,
    tickerText: 'Selamat Datang di Portal Resmi Musyawarah Guru Mata Pelajaran (MGMP) IPA Kecamatan Bengkalis • Menguatkan Kompetensi Pendidik Sains & Menumbuhkan Generasi Berpikir Kritis • Hubungi Sekretariat: mgmpipabkls@gmail.com',
    accreditationTickerEnabled: true,
    accreditationTickerText: '[MGMP] Musyawarah Guru Mata Pelajaran IPA Kecamatan Bengkalis • [WILAYAH] Kec. Bengkalis, Kab. Bengkalis - Riau • [KOMBEL] Komunitas Belajar Terdaftar Kemendikbudristek • [KONTAK] mgmpipabkls@gmail.com',
    accreditationTickerSpeed: 'normal',
    primaryColor: 'blue',
  },
  importantAnnouncement: {
    enabled: false,
    badge: 'INFO MGMP',
    text: '',
    theme: 'info',
    speed: 'normal',
    buttonEnabled: false,
    buttonText: '',
    buttonUrl: '',
    isMarquee: true,
    isSticky: true,
  },
  header: {
    heroTitle: 'Musyawarah Guru Mata Pelajaran (MGMP) IPA Kecamatan Bengkalis',
    heroSubtitle: 'Mewujudkan pembelajaran sains (Ilmu Pengetahuan Alam) yang inovatif, eksploratif, dan berpusat pada peserta didik di seluruh SMP dan MTs se-Kecamatan Bengkalis.',
    heroImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=1600&auto=format&fit=crop&q=80',
    heroCtaText: 'Jelajahi Program & Berita',
    heroCtaLink: '#berita',
    secondaryCtaText: 'Agenda Kegiatan',
    secondaryCtaLink: '#agenda',
    highlights: [
      { id: 'stat-1', icon: 'Users', label: 'Guru Anggota IPA', value: '45+' },
      { id: 'stat-2', icon: 'GraduationCap', label: 'SMP / MTs Tergabung', value: '24 Sekolah' },
      { id: 'stat-3', icon: 'BookOpen', label: 'Modul & LKPD IPA', value: '60+ Karya' },
      { id: 'stat-4', icon: 'Award', label: 'Program & Workshop', value: '100% Aktif' },
    ],
  },
  navMenus: [
    { id: 'menu-beranda', label: 'Beranda', path: '#beranda', isDropdown: false, enabled: true },
    {
      id: 'menu-profil',
      label: 'Profil MGMP',
      path: '#sambutan',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'sub-p1', label: 'Sambutan Ketua MGMP', path: '#sambutan', description: 'Visi & arahan Ketua MGMP IPA Bengkalis' },
        { id: 'sub-p2', label: 'Visi, Misi & Tujuan', path: '#sambutan', description: 'Arah gerak peningkatan mutu pendidik sains' },
        { id: 'sub-p3', label: 'Struktur Pengurus', path: '#sambutan', description: 'Susunan pengurus dan koordinator bidang' },
      ],
    },
    { id: 'menu-program', label: 'Program Kerja', path: '#fasilitas', isDropdown: false, enabled: true },
    {
      id: 'menu-berita',
      label: 'Publikasi & Sains',
      path: '#berita',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'sub-b1', label: 'Kabar Kegiatan MGMP', path: '#berita', description: 'Dokumentasi musyawarah dan pelatihan' },
        { id: 'sub-b2', label: 'Praktikum & Modul Ajar', path: '#berita', description: 'Inovasi LKPD dan perangkat ajar IPA' },
        { id: 'sub-b3', label: 'Prestasi & Karya Guru', path: '#berita', description: 'Capaian dan pembinaan olimpiade sains' },
      ],
    },
    { id: 'menu-agenda', label: 'Agenda', path: '#agenda', isDropdown: false, enabled: true },
    { id: 'menu-kontak', label: 'Kontak', path: '#kontak', isDropdown: false, enabled: true },
  ],
  layoutSections: {
    showHero: true,
    showQuickStats: true,
    showAccreditation: true,
    showPrincipalSpeech: true,
    showNews: true,
    showAgenda: true,
    showFacilities: true,
    showExtracurriculars: true,
    showVideoEmbed: false,
    showMapEmbed: false,
    showPublicComments: true,
  },
  mobileBottomNav: {
    enabled: true,
    showHome: true,
    showNews: true,
    showAchievements: false,
    showExtracurriculars: true,
    showContact: true,
    styleVariant: 'floating-dock',
    themeColor: 'dark-slate',
    accentColor: 'blue',
    showLabels: false,
    elevatedCenterButton: true,
    showActiveIndicator: true,
  },
  principal: {
    name: 'Ketua MGMP IPA Kecamatan Bengkalis',
    title: 'Ketua MGMP IPA Kec. Bengkalis',
    nip: '-',
    imageUrl: '',
    quote: 'Melalui musyawarah dan kolaborasi yang solid, kita jadikan pembelajaran IPA di Kecamatan Bengkalis semakin kontekstual, menyenangkan, dan menginspirasi rasa ingin tahu peserta didik.',
    fullSpeech: '<p><strong>Assalamu’alaikum Warahmatullahi Wabarakatuh,</strong></p><p>Selamat datang di portal resmi <strong>Musyawarah Guru Mata Pelajaran (MGMP) IPA Kecamatan Bengkalis</strong>. Wadah ini dihadirkan sebagai sarana komunikasi, diseminasi informasi, serta pusat berbagi praktik baik <em>(best practice)</em> bagi seluruh guru mata pelajaran Ilmu Pengetahuan Alam tingkat SMP dan MTs di wilayah Kecamatan Bengkalis.</p><p>Pendidikan sains memiliki peranan strategis dalam membangun keterampilan berpikir kritis, kreativitas, dan literasi sains anak bangsa. Melalui MGMP IPA, kami berkomitmen untuk terus meningkatkan kompetensi profesional pendidik melalui workshop kurikulum merdeka, pelatihan pemanfaatan laboratorium dan alat peraga edukatif, serta penyusunan modul pembelajaran yang interaktif dan menyenangkan.</p><p>Kami mengajak seluruh rekan pendidik untuk aktif berpartisipasi dan berkontribusi. Mari bersama-sama bersinergi demi kemajuan mutu pendidikan sains di Kabupaten Bengkalis.</p><p><strong>Wassalamu’alaikum Warahmatullahi Wabarakatuh.</strong></p>',
  },
  embeds: {
    youtubeTitle: 'Dokumentasi Video Praktikum & Musyawarah MGMP IPA',
    youtubeSubtitle: 'Melihat langsung kolaborasi pendidik sains dalam eksperimen laboratorium dan workshop inovasi media pembelajaran.',
    youtubeUrl: '',
    mapTitle: 'Sekretariat & Wilayah Kerja MGMP IPA Kecamatan Bengkalis',
    mapIframeUrl: '',
  },
  facilities: [
    {
      id: 'fac-1',
      title: 'Laboratorium Sains & Eksperimen',
      category: 'Sains',
      imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&auto=format&fit=crop&q=80',
      description: 'Panduan dan standarisasi praktikum fisika, kimia, dan biologi berbasis bahan lokal serta peralatan laboratorium standar sekolah.',
    },
    {
      id: 'fac-2',
      title: 'Bank Modul & Lembar Kerja (LKPD)',
      category: 'Literasi',
      imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
      description: 'Koleksi modul ajar berdiferensiasi, kisi-kisi asesmen sumatif, dan perangkat ajar Kurikulum Merdeka karya guru-guru IPA Bengkalis.',
    },
    {
      id: 'fac-3',
      title: 'Laboratorium Virtual & Simulasi PhET',
      category: 'Teknologi',
      imageUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&auto=format&fit=crop&q=80',
      description: 'Pemanfaatan media digital interaktif, simulasi sains virtual, dan aplikasi eksperimen untuk visualisasi konsep sains abstrak.',
    },
    {
      id: 'fac-4',
      title: 'Pojok Inovasi Alat Peraga IPA',
      category: 'Umum',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
      description: 'Dokumentasi inovasi alat peraga edukatif sains murah dan ramah lingkungan hasil kreasi guru dan siswa se-Kecamatan Bengkalis.',
    },
  ],
  extracurriculars: [
    {
      id: 'ekskul-1',
      name: 'Pembinaan Olimpiade Sains (OSN IPA)',
      category: 'Sains & Riset',
      coach: 'Tim Pengembang OSN MGMP IPA',
      schedule: 'Setiap Menjelang Seleksi Kabupaten',
      icon: 'Trophy',
      description: 'Program pembimbingan intensif dan bedah bank soal olimpiade sains bagi guru pembina dan siswa berprestasi di tingkat SMP/MTs.',
      imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ekskul-2',
      name: 'Komunitas Belajar (Kombel) Guru IPA',
      category: 'Organisasi / Komunitas',
      coach: 'Koordinator Kurikulum MGMP',
      schedule: 'Pertemuan Rutin Bulanan',
      icon: 'Users',
      description: 'Forum diskusi rutin pemecahan problem pembelajaran, asesmen diagnostik, dan strategi pembelajaran sains kontekstual.',
      imageUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ekskul-3',
      name: 'Workshop Pembuatan Media & Kit Praktikum',
      category: 'Teknologi & Inovasi',
      coach: 'Narasumber & Guru Praktisi',
      schedule: 'Program Semesteran',
      icon: 'Cpu',
      description: 'Pelatihan teknis perakitan media pembelajaran sains interaktif memanfaatkan potensi lingkungan pesisir Bengkalis.',
      imageUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&auto=format&fit=crop&q=80',
    },
    {
      id: 'ekskul-4',
      name: 'Karya Tulis Ilmiah & Penelitian Tindakan Kelas (PTK)',
      category: 'Literasi & Publikasi',
      coach: 'Tim Penjamin Mutu MGMP',
      schedule: 'Berkala',
      icon: 'BookOpen',
      description: 'Pendampingan penulisan PTK, artikel ilmiah pendidikan sains, dan publikasi jurnal untuk pengembangan profesionalisme berkelanjutan.',
      imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop&q=80',
    },
  ],
  agendas: [
    {
      id: 'agenda-1',
      title: 'Musyawarah Kerja Rutin Guru IPA & Bedah Modul Ajar Semester Ganjil',
      date: 'Sabtu, 28 Oktober 2026',
      time: '08.30 - 12.30 WIB',
      location: 'Sekretariat MGMP IPA / SMPN Rujukan Bengkalis',
      category: 'Musyawarah Rutin',
      isVisible: true,
    },
    {
      id: 'agenda-2',
      title: 'Workshop Pemanfaatan Kit Praktikum IPA & Laboratorium Ramah Lingkungan',
      date: 'Kamis, 12 November 2026',
      time: '09.00 - 15.00 WIB',
      location: 'Laboratorium IPA Terpadu Bengkalis',
      category: 'Pelatihan',
      isVisible: true,
    },
    {
      id: 'agenda-3',
      title: 'Simulasi dan Pendampingan Lomba Karya Sains / OSN IPA SMP',
      date: 'Sabtu, 05 Desember 2026',
      time: '08.00 - 12.00 WIB',
      location: 'Aula Gedung Guru Bengkalis',
      category: 'Olimpiade',
      isVisible: true,
    },
  ],
  facilitiesTabTitle: 'Sarana & Sumber Belajar IPA',
  ekskulTabTitle: 'Program Kerja & Kombel',
  facilitiesSectionTitle: 'Sarana Belajar & Program Kerja Unggulan',
  facilitiesSectionSubtitle: 'Dukungan media praktikum sains interaktif serta wadah kolaborasi peningkatan kompetensi guru IPA.',
  footer: {
    aboutText: 'Musyawarah Guru Mata Pelajaran (MGMP) Ilmu Pengetahuan Alam (IPA) Kecamatan Bengkalis merupakan forum resmi pendidik sains jenjang SMP dan MTs dalam memperkuat kompetensi pedagogik, profesional, dan kolaborasi demi kemajuan mutu pendidikan di Kabupaten Bengkalis, Provinsi Riau.',
    address: 'Kecamatan Bengkalis, Kabupaten Bengkalis, Riau 28712',
    phone: '-',
    whatsapp: '-',
    email: 'mgmpipabkls@gmail.com',
    openingHours: 'Senin - Sabtu: 08.00 - 16.00 WIB',
    socialLinks: {
      instagram: '',
      youtube: '',
      facebook: '',
      twitter: '',
    },
    copyright: '© MGMP IPA Kecamatan Bengkalis • Hak Cipta Dilindungi',
  },
  themeConfig: DEFAULT_THEME_CONFIG,
  googleAppsScript: {
    enabled: true,
    webAppUrl: DEFAULT_APPS_SCRIPT_WEB_APP_URL || '',
    folderId: DEFAULT_APPS_SCRIPT_FOLDER_ID || '',
    spreadsheetId: '',
    autoCreateFolder: true,
    testStatus: 'untested',
  },
};

// Initial starter articles for MGMP IPA Kecamatan Bengkalis
export const DEFAULT_NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 'post-mgmp-1',
    title: 'Musyawarah Kerja Awal Semester Guru IPA SMP/MTs Se-Kecamatan Bengkalis',
    slug: 'musyawarah-kerja-awal-semester-guru-ipa-bengkalis',
    summary: 'Forum silaturahmi dan penyusunan program kerja MGMP IPA Kecamatan Bengkalis dalam rangka penguatan implementasi Kurikulum Merdeka dan asesmen sains.',
    content: '<p>Musyawarah Guru Mata Pelajaran (MGMP) IPA Kecamatan Bengkalis menyelenggarakan pertemuan kerja awal semester yang dihadiri oleh perwakilan guru IPA dari seluruh SMP dan MTs baik negeri maupun swasta se-Kecamatan Bengkalis.</p><p>Pertemuan ini berfokus pada penyelarasan Alur Tujuan Pembelajaran (ATP), perancangan modul ajar berdiferensiasi, serta pemanfaatan sarana laboratorium untuk praktikum sains kontekstual. Dengan semangat gotong royong dan kolaborasi, para pendidik sains berkomitmen menciptakan suasana belajar yang merangsang daya kritis dan rasa ingin tahu peserta didik.</p><p>Hasil dari musyawarah ini akan ditindaklanjuti dengan serangkaian lokakarya mini dan diseminasi perangkat ajar di masing-masing satuan pendidikan.</p>',
    author: 'Pengurus MGMP IPA Bengkalis',
    date: '15 September 2026',
    category: 'Kegiatan',
    coverImage: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&auto=format&fit=crop&q=80',
    views: 182,
    isPinned: true,
    likes: 24,
    status: 'published',
  },
  {
    id: 'post-mgmp-2',
    title: 'Workshop Praktikum Sains Ramah Lingkungan & Pembuatan Alat Peraga IPA Berbasis Bahan Lokal',
    slug: 'workshop-praktikum-sains-ramah-lingkungan-alat-peraga-ipa',
    summary: 'Pelatihan pembuatan kit eksperimen sains sederhana memanfaatkan material pesisir dan limbah daur ulang untuk menunjang pembelajaran aktif di laboratorium.',
    content: '<p>Keterbatasan sarana laboratorium tidak lagi menjadi halangan untuk menyajikan praktikum sains yang memukau bagi siswa. Melalui workshop yang digelar MGMP IPA Kecamatan Bengkalis, para guru dilatih membuat alat peraga sains sederhana namun memiliki akurasi konsep yang tinggi.</p><p>Materi pelatihan meliputi perakitan indikator asam-basa alami dari ekstrak tumbuhan lokal Bengkalis, model sistem pernapasan manusia sederhana, hingga simulasi hukum Archimedes menggunakan botol plastik bekas. Seluruh peserta sangat antusias mempraktikkan langsung karya alat peraga yang siap diterapkan di ruang kelas.</p>',
    author: 'Tim Laboratorium MGMP',
    date: '02 September 2026',
    category: 'Akademik',
    coverImage: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    views: 245,
    isPinned: true,
    likes: 38,
    status: 'published',
  },
  {
    id: 'post-mgmp-3',
    title: 'Pembinaan Intensif Olimpiade Sains Nasional (OSN) IPA SMP Tingkat Kecamatan Bengkalis',
    slug: 'pembinaan-intensif-olimpiade-sains-nasional-ipa-bengkalis',
    summary: 'Kolaborasi guru-guru pembina MGMP IPA dalam menyeleksi dan membimbing talenta-talenta muda sains menuju kompetisi tingkat kabupaten dan provinsi.',
    content: '<p>Dalam rangka mempersiapkan bibit-bibit unggul di bidang sains, MGMP IPA Kecamatan Bengkalis menginisiasi program bimbingan terpadu OSN IPA jenjang SMP. Program ini melibatkan tutor dari guru-guru senior yang berpengalaman dalam melatih soal-soal olimpiade tingkat kabupaten dan nasional.</p><p>Fokus pembinaan mencakup penalaran konsep biologi sel, ekologi, mekanika, fluida, serta analisis grafik eksperimen sains. Diharapkan perwakilan sekolah dari Kecamatan Bengkalis mampu menorehkan prestasi gemilang di kancah yang lebih tinggi.</p>',
    author: 'Koordinator OSN MGMP IPA',
    date: '20 Agustus 2026',
    category: 'Prestasi',
    coverImage: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80',
    views: 139,
    isPinned: false,
    likes: 19,
    status: 'published',
  },
  {
    id: 'post-mgmp-4',
    title: 'Pendaftaran dan Pemutakhiran Database Keanggotaan Guru IPA Kecamatan Bengkalis',
    slug: 'pendaftaran-pemutakhiran-database-keanggotaan-guru-ipa',
    summary: 'Seluruh pendidik mata pelajaran IPA tingkat SMP dan MTs dihimbau melakukan verifikasi data anggota untuk penerbitan sertifikat kegiatan PKB dan Kombel.',
    content: '<p>Diberitahukan kepada seluruh Bapak/Ibu Guru pengampu mata pelajaran Ilmu Pengetahuan Alam (IPA) jenjang SMP dan MTs di lingkungan Kecamatan Bengkalis agar segera memperbarui biodata keanggotaan pada sistem pendataan MGMP.</p><p>Pemutakhiran data ini diperlukan guna penerbitan sertifikat resmi kegiatan Pengembangan Keprofesian Berkelanjutan (PKB), pembagian kelompok kerja komunitas belajar (Kombel), serta distribusi materi dan modul ajar IPA terbaru.</p><p>Informasi dan konfirmasi pendaftaran dapat menghubungi sekretariat MGMP melalui email resmi: <strong>mgmpipabkls@gmail.com</strong>.</p>',
    author: 'Sekretariat MGMP IPA',
    date: '10 Agustus 2026',
    category: 'Pengumuman',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
    views: 98,
    isPinned: false,
    likes: 15,
    status: 'published',
  },
];


